# Generated by Django 3.1.5 on 2021-01-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registered_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('email_address', models.EmailField(max_length=254)),
                ('verified_email', models.BooleanField(default=False)),
            ],
        ),
    ]
