# Generated by Django 3.1.5 on 2021-01-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0002_auto_20210108_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_accounts',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
