# Generated by Django 3.1.5 on 2021-01-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0003_auto_20210111_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_accounts',
            old_name='verified_email',
            new_name='is_email_verified',
        ),
    ]
